### ISSUE TITLE
Function readMeasurementData returns integer on Arduino Due

### ISSUE THREAD

**Issue by dmoimas** [Sensirion/arduino-i2c-sfm-sf06#1]
Plaform: Arduino Due (SAM board package 1.6.12)
File: SensirionI2CSfmSf06.cpp
Function: SensirionI2CSfmSf06::readMeasurementData

`flow = (intFlow - _flowOffset) / _flowScaleFactor;`
should be changed to:
`flow = (float)(intFlow - _flowOffset) / (float)(_flowScaleFactor);`

otherwise it returns integer values.

Edit: typo in SAM board package version

**Comment by psachs** [comment]
thanks for pointing this out. We will post an updated driver once this issue is resolved
