### ISSUE TITLE
SFM4300-50-P

### ISSUE THREAD

**Issue by ghost** [Sensirion/arduino-i2c-sfm-sf06#2]
Hi,
Thanks for creating this library, very easy to use.
I have a problem when using a SFM4300-50-P. When the flow rate is over 32 l/min, the value becomes negative (-32, then, the higher the flow, the lower this negative value, -30, -28, etc.). Could it be a problem of coding a byte operation?

I do not experience this problem when using a SFM4300-20-P, which is limited to 20 l/min.

Thanks

**Comment by sdmueller** [comment]
Hi @gduplessi

This looks like a bug in the library to me.
Could be because we are using `int16` instead of `uint16` for the flow and the value overflows into the negative.

I will create an internal bug ticket, so that we can investigate this issue.

Thanks for pointing this out!

**Comment by LeonieFierz** [comment]
Dear @gduplessi 
I checked our implementation, data types of the raw value read from the sensor and the conversion to the physical value should be ok.
Which Gas did you try to measure when getting the odd flow rates? Please note that the SFM4300-50-P version supports less Gas and Gas mixtures (namely O2, Air, O2/Air) than the SFM4300-20-P.

**Comment by ghost** [comment]
Hello,
I am measuring Air with the SFM4300-50-P and I can confirm it was a problem of overflow.
What I did is to modify the .h file to make _flowOffset and _flowScaleFactor public and then created this function:

```
void readSFM4300() {
  uint16_t error;
  char errorMessage[256];
  int16_t flow = 0;
  int16_t temperature = 0;
  int32_t difference = 0;
  uint16_t status = 0;
  error = sfmSf06.readMeasurementDataRaw(flow, temperature, status);
  if(!error){
    int32_t flow32 = (int32_t) flow;
    int32_t _flowOffset32 = (int32_t) sfmSf06._flowOffset;
    difference = flow32 - _flowOffset32;
    volFlowRateSFM4300 = (float) difference/ sfmSf06._flowScaleFactor;
  }
}
```

**Comment by LeonieFierz** [comment]
@gduplessi 
Thank you for reporting back. I fixed the overflow when converting the raw flow and created a new driver version 0.1.1 which fixes the overflow.
Best, Léonie

**Comment by praviksha1801** [comment]
Hi
Thank you for creating library, for very easy use
I have configured SFM4300-20-P with arduino mega 2560 in which facing of issue flow rate over 12or13l/m value becomes negative. also after overlaping range it becomes 0 (request for support showing final range limit)
