### ISSUE TITLE
SFM4300-20-P Negative value 

### ISSUE THREAD

**Issue by praviksha1801** [Sensirion/arduino-i2c-sfm-sf06#3]
Hi
Thank you for creating library, for very easy use.
I have configured SFM4300-20-P with Arduino mega 2560 in which facing of issue flow rate over 12 or 13 l/m value becomes negative. also after overlapping range it becomes 0 (request for support showing final range limit).

**Comment by LeonieFierz** [comment]
Hi,
thank you for reporting this issue. It is due to an overflow when converting from the raw values to physical flow. We fixed the bug on the master branch.
Best, Léonie

**Comment by praviksha1801** [comment]
Thank you so much as its resolved effectively and application runs successful
