### ISSUE TITLE
SFM-3013-300-CL Wiring Diagram Arduino Mega

### ISSUE THREAD

**Issue by shikharsingh2499** [Sensirion/arduino-i2c-sfm-sf06#4]
Hi, 

Our team is attempting to connect SIX SFM-3013-300-CL Mass Flow Rate (MFR) Sensors to an Arduino Mega and get a readable output on a Laptop. This would require a multiplexer to enable multiple sensors to be integrated. The datasheet states the requirement for a 3.3kohm pull-up resistor to be fitted. Do these resistors need to be connected one to each the SDL and SCL port of each MFR sensor and then to the multiplexer? Would any additional components/resistors be required for this wiring diagram, and is this the right way to set up the system?

Thanks

**Comment by LeonieFierz** [comment]
Hi,

thank you for contacting us.

To connect 6 SFM-3013-300-CL sensor to the Arduino Mega you are right that a Multiplexer is needed. However, if you connect to the SCL/SDA pin of the Arudino Board the pull up resistors are on the board already and you do not need additional pull-up resistors.

You will have to adapt the example code from this repo to work with the multiplexer, namely choose the multiplexer line before communicating with a sensor. You can have a look at the tutorial for LiquiFlow sensors which is quite similar to the SFM Sensors: https://developer.sensirion.com/archive/tutorials/arduino-interface-for-multiple-sf06-liquid-flow-sensors/ and the example code can be found here: https://github.com/Sensirion/arduino-liquid-flow-snippets/blob/master/SF06/example_20_simple_measurement_multiple_SLF3x/example_20_simple_measurement_multiple_SLF3x.ino

Best, Léonie

**Comment by shikharsingh2499** [comment]
Hi, 

Thanks for sharing your input and relevant resources. To confirm, we will be using a TCA9548A multiplexer (as used for the SF06 sensors) to connect the 6 SFM3013 sensors to the Arduino board. We understand the Arduino board has pull-up resistors on the SDA and SCL ports, but they would only work for the case of connecting just 1 sensor to the Arduino board directly, and there would not be enough ports for 6 (hence requirement for a multiplexer), is that correct? 

In the case of using a multiplexer to wire 6 SFM3013 sensors: The TCA9548A multiplexer has pull-up resistors but only on the main SDA and SCL ports, the sub-i2c bus sets (SD0/SC0-SD7/SC7) do not have resistors. We wanted to confirm if a 3.3kohm resistor would have to be placed on both the SDx and SCx pins between each sensor and the multiplexer? 

We are also unable to understand the use of the two resistors connected to the Arduino coming from the multiplexer in the sf06 example and how this would translate/impact what we are trying to do. 

Would it be worthwhile for us to produce a circuit diagram that you can aid approve to ensure we are wiring things correctly? 

Appreciate your support. Thanks. 

Shikhar

**Comment by LeonieFierz** [comment]
Hi Shikhar,
the Pull Ups between the Multiplexer and Arduino would only be necessary if the Arduino has no Pull Ups built in, so you should not need them. 
For the Pull Ups between the Sensor and Multiplexer, it depends what exactly the Multiplexer does. Best would be to measure if SDA and SCL lines to your Sensors are on high voltage level in idle mode. In general, you need a pull up on SDA and SCL line, as I2C defines for both lines high level in idle state. 
Best, Léonie

**Comment by shikharsingh2499** [comment]
Thanks for the support, we'll refer to the relevant datasheets to confirm. 

Appreciate the help. 

Shikhar
