### ISSUE TITLE
SFM3013 Arduino Interface Issue

### ISSUE THREAD

**Issue by shikharsingh2499** [Sensirion/arduino-i2c-sfm-sf06#5]
Hi, 

I am trying to connect an SFM-3013-CL to an Arduino Mega and I'm using this repo ([arduino-i2c-sfm-sf06](https://github.com/Sensirion/arduino-i2c-sfm-sf06)) as guidance to collect Temperature and Mass Flow Readings. Following is the Circuit Set-Up I've been using:

![image](https://github.com/Sensirion/arduino-i2c-sfm-sf06/assets/90009138/2b348afc-17f7-4301-8758-66c010af05e8)

I have followed the guidance and downloaded the 'Sensirion I2C SFM-SF06' Library and also installed all the required dependencies onto the Arduino IDE. I decided to download and use the latest 'exampleUsage' file (1.4.0), SensirionI2cSfmSf06.h and SensirionI2cSfmSf06.cpp. 

Following is the code I've used (from the exampleUsage file):

`
#include <Arduino.h>
#include <SensirionI2cSfmSf06.h>
#include <Wire.h>

SensirionI2cSfmSf06 sensor;

static char errorMessage[64];
static int16_t error;

void print_byte_array(uint8_t* array, uint16_t len) {
    uint16_t i = 0;
    Serial.print("0x");
    for (; i < len; i++) {
        Serial.print(array[i], HEX);
    }
}

void setup() {

    Serial.begin(115200);
    while (!Serial) {
        delay(100);
    }
    Wire.begin();
    sensor.begin(Wire, SFM3013_I2C_ADDR_2F);

    sensor.stopContinuousMeasurement();
    delay(100);
    uint32_t productIdentifier = 0;
    uint8_t serialNumber[8] = {0};
    error = sensor.readProductIdentifier(productIdentifier, serialNumber, 8);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute readProductIdentifier(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    Serial.print("productIdentifier: ");
    Serial.print(productIdentifier);
    Serial.print("\t");
    Serial.print("serialNumber: ");
    print_byte_array(serialNumber, 8);
    Serial.println();
    error = sensor.startO2ContinuousMeasurement();
    if (error != NO_ERROR) {
        Serial.print(
            "Error trying to execute startO2ContinuousMeasurement(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
}

void loop() {

    float aFlow = 0.0;
    float aTemperature = 0.0;
    uint16_t aStatusWord = 0u;
    delay(100);
    error = sensor.readMeasurementData(aFlow, aTemperature, aStatusWord);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute readMeasurementData(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    Serial.print("aFlow: ");
    Serial.print(aFlow);
    Serial.print("\t");
    Serial.print("aTemperature: ");
    Serial.print(aTemperature);
    Serial.print("\t");
    Serial.print("aStatusWord: ");
    Serial.print(aStatusWord);
    Serial.println();
}
`

However, upon running this, the serial monitor shows a maximum of 2-3 readings, and then stops displaying data and prints unreadable symbols: 
![image](https://github.com/Sensirion/arduino-i2c-sfm-sf06/assets/90009138/2e2cc7f1-62f4-418c-9802-36c5e1b15291)

Would appreciate if I could get guidance on what I am doing incorrectly, and how to resolve this. 

Thanks.

**Comment by quentin-cy** [comment]
Hej,

This behavior is sometimes caused by an incorrect baud-rate used by the serial monitor.
It should be 115200. can you confirm you are using that value ?

Hope it helps

**Comment by shikharsingh2499** [comment]
> Hej,
> 
> This behavior is sometimes caused by an incorrect baud-rate used by the serial monitor. It should be 115200. can you confirm you are using that value ?
> 
> Hope it helps

Hi, 

Works after changing it to 115200. 

Thanks.
