### ISSUE TITLE
SFM3013-300-CL Code Issue for connecting multiple sensors with Multiplexer(TCA9548A)

### ISSUE THREAD

**Issue by shikharsingh2499** [Sensirion/arduino-i2c-sfm-sf06#6]
Hi, I am trying to connect two SFM-3013-300-CL's to an Arduino via a TCA9548A multiplexer to collect flow and temperature data. I am using the 'exampleusage.ino' file and have set the I2C multiplexer as specified. However I keep receiving the following error: `Error trying to execute readMeasurementData(): Not enough data received`

![image](https://github.com/Sensirion/arduino-i2c-sfm-sf06/assets/90009138/39f6969a-6a2b-4603-a5d2-795c2b736bb4)

I am trying the to run the multiplexer with two sensors to test if it works with the following code: 

`#include <Arduino.h>
#include <SensirionI2cSfmSf06.h>
#include <Wire.h>

#define TCAADDR 0x70
int active_sensors[8];

SensirionI2cSfmSf06 sensor;
SensirionI2cSfmSf06 sensor_2;

void tcaselect(uint8_t i) {                        // i stands for bus
  if (i > 7) return;
  Wire.beginTransmission(TCAADDR);
  Wire.write(1 << i);                     // send byte to select bus
  Wire.endTransmission();
}

static char errorMessage[64];
static int16_t error;

void print_byte_array(uint8_t* array, uint16_t len) {
    uint16_t i = 0;
    Serial.print("0x");
    for (; i < len; i++) {
        Serial.print(array[i], HEX);
    }
}

void setup() {

    Serial.begin(115200);
    while (!Serial) {
        delay(100);
    }
    Wire.begin();
    tcaselect(1);
    sensor.begin(Wire, SFM3013_I2C_ADDR_2F);

    tcaselect(1);
    sensor.stopContinuousMeasurement();
    delay(100);
    uint32_t productIdentifier = 0;
    uint8_t serialNumber[8] = {0};
    error = sensor.readProductIdentifier(productIdentifier, serialNumber, 8);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute readProductIdentifier(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    Serial.print("productIdentifier: ");
    Serial.print(productIdentifier);
    Serial.print("\t");
    Serial.print("serialNumber: ");
    print_byte_array(serialNumber, 8);
    Serial.println();
    tcaselect(1);
    error = sensor.startO2ContinuousMeasurement();
    if (error != NO_ERROR) {
        Serial.print(
            "Error trying to execute startO2ContinuousMeasurement(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }

    tcaselect(2);
    sensor.begin(Wire, SFM3013_I2C_ADDR_2F);

    tcaselect(2);
    sensor.stopContinuousMeasurement();
    delay(100);
    uint32_t productIdentifier = 0;
    uint8_t serialNumber[8] = {0};
    error = sensor.readProductIdentifier(productIdentifier, serialNumber, 8);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute readProductIdentifier(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    Serial.print("productIdentifier: ");
    Serial.print(productIdentifier);
    Serial.print("\t");
    Serial.print("serialNumber: ");
    print_byte_array(serialNumber, 8);
    Serial.println();
    tcaselect(2);
    error = sensor.startO2ContinuousMeasurement();
    if (error != NO_ERROR) {
        Serial.print(
            "Error trying to execute startO2ContinuousMeasurement(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
}

void loop() {

    float aFlow = 0.0;
    float aTemperature = 0.0;
    uint16_t aStatusWord = 0u;
    delay(100);
    tcaselect(1);
    error = sensor.readMeasurementData(aFlow, aTemperature, aStatusWord);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute readMeasurementData(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    Serial.print("aFlow: ");
    Serial.print(aFlow);
    Serial.print("\t");
    Serial.print("aTemperature: ");
    Serial.print(aTemperature);
    Serial.print("\t");
    Serial.print("aStatusWord: ");
    Serial.print(aStatusWord);
    Serial.println();

    tcaselect(2);
    error = sensor.readMeasurementData(aFlow, aTemperature, aStatusWord);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute readMeasurementData(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    Serial.print("aFlow: ");
    Serial.print(aFlow);
    Serial.print("\t");
    Serial.print("aTemperature: ");
    Serial.print(aTemperature);
    Serial.print("\t");
    Serial.print("aStatusWord: ");
    Serial.print(aStatusWord);
    Serial.println();
}`

Would appreciate any guidance.

**Comment by quentin-cy** [comment]
Hej thanks for reaching out. 
So you do not get any error message before getting to readMeasurement ?
You also checking the sensors with the example code without the multiplexer ?

**Comment by shikharsingh2499** [comment]
> Hej thanks for reaching out. So you do not get any error message before getting to readMeasurement ? You also checking the sensors with the example code without the multiplexer ?

Hi, thanks for getting back. 

To confirm, I do not get any error message before getting to readMeasurement. 

I have run the example code without the multiplexer (sensor connected to arduino directly) with just one sensor, and it prints the output normally.

 I have also tried running the example code (with Multiplexer lines) with the multiplexer and only one sensor, but it pulls the same readMeasurement error (not enough data received) as before. 

To confirm that the multiplexer is working, I ran code from Adafruit to check that it is reading the sensors at the SC0, SD0, SC1, and SD1 ports and it confirms that it is able to read the sensors at those ports/address.

**Comment by quentin-cy** [comment]
Between this step:

> I have run the example code without the multiplexer (sensor connected to arduino directly) with just one sensor, and it prints the output normally.

and this one: 

> I have also tried running the example code (with Multiplexer lines) with the multiplexer and only one sensor, but it pulls the same readMeasurement error (not enough data received) as before.

you used the same sensor ? ( sorry if the question sound stupid but better be sure that it is not a faulty sensor)

The only thing I see in your code is that you call tcaselect sometimes unnecessarily. Should only be needed when actually switching output right ?

Can you share your example with one sensor attached to the multiplexer ?
we should start there

EDIT: Sorry we do not have the HW on our side to investigate

**Comment by shikharsingh2499** [comment]
> Between this step:
> 
> > I have run the example code without the multiplexer (sensor connected to arduino directly) with just one sensor, and it prints the output normally.
> 
> and this one:
> 
> > I have also tried running the example code (with Multiplexer lines) with the multiplexer and only one sensor, but it pulls the same readMeasurement error (not enough data received) as before.
> 
> you used the same sensor ? ( sorry if the question sound stupid but better be sure that it is not a faulty sensor)

Yep I used the same sensor for both instances. 

> The only thing I see in your code is that you call tcaselect sometimes unnecessarily. Should only be needed when actually switching output right ?

It would make sense to only call tcaselect when switching output - I decided to call it multiple times after reading guidance from an Arduino forum: https://forum.arduino.cc/t/using-pca9548a-multiplexer-for-multiple-sensirion-sfm3003-gas-flow-sensors/1161685/2

> Can you share your example with one sensor attached to the multiplexer ? we should start there

As an update: I managed to make the sensors work now - all 6 connected to the multiplexer - turns out that the SD1 and SC1 ports of the multiplexer were not reading data, and I decided to use the other ports instead - which turned out well. 

Thanks for your support on the above and your continued responses. Happy to share the working code here if you'd like. 

> EDIT: Sorry we do not have the HW on our side to investigate

**Comment by quentin-cy** [comment]
Hej @shikharsingh2499 ,

Thanks for coming back to us and closing the issue.
It is great to hear that you found the issue and got it working.
I think an example usage with multiplexer would be great indeed, unfortunately our drivers are generated which makes it hard to take in contributions ... we are working on that though, hopefully it will be easier in the future.
We might try to replicate the setup in an Hackster post in the future.

Have fun and success with you project
Cheers
Q
